import { createHash } from 'node:crypto';
import { Client } from '@modelcontextprotocol/client';
import { InMemoryTransport, type McpServer } from '@modelcontextprotocol/server';

/**
 * What a caller can reach, read from the server rather than from your notes.
 *
 * A permission map has to name every capability a server registers, and nothing
 * generates that list today — you write it by hand and hope. This connects a
 * real client to your own server over an in-memory pair and asks it, so the
 * answer is the one a caller would get.
 *
 * Build the server *ungated* here. A gated server answers per principal, so
 * listing one would hand you a map missing exactly the capabilities that most
 * need a price.
 */

export type CapabilityRecord = {
  /** Every capability, labelled as `gate()` labels them, sorted. */
  names: string[];
  /** A digest per capability, so a snapshot can catch one changing under you. */
  fingerprints: Record<string, string>;
};

function digest(parts: unknown): string {
  return createHash('sha256')
    .update(JSON.stringify(canonical(parts)))
    .digest('hex')
    .slice(0, 16);
}

/**
 * Key order is an accident of how a value was built, so sort it away. Without
 * this an SDK that emitted the same definition in a different order would churn
 * every fingerprint in a snapshot and teach people to ignore the diff.
 */
function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([key, inner]) => [key, canonical(inner)]),
    );
  }
  return value;
}

export async function recordCapabilities(
  factory: () => McpServer | Promise<McpServer>,
): Promise<CapabilityRecord> {
  const server = await factory();
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);
  const client = new Client({ name: 'mcp-authz-record-capabilities', version: '1.0.0' });
  await client.connect(clientTransport);

  try {
    const [tools, prompts, resources, templates] = await Promise.all([
      client.listTools(),
      client.listPrompts(),
      client.listResources(),
      client.listResourceTemplates(),
    ]);
    const labelled: [string, unknown][] = [
      ...tools.tools.map((tool) => [tool.name, tool] as [string, unknown]),
      ...prompts.prompts.map((prompt) => [`prompt:${prompt.name}`, prompt] as [string, unknown]),
      ...resources.resources.map((resource) => [`resource:${resource.name}`, resource] as [string, unknown]),
      ...templates.resourceTemplates.map(
        (template) => [`resource:${template.name}`, template] as [string, unknown],
      ),
    ];
    const names = labelled.map(([label]) => label).sort();
    const byLabel = new Map(labelled);
    const fingerprints: Record<string, string> = {};
    for (const label of names) {
      // The whole definition as served, not a chosen handful of fields. A tool
      // has an inputSchema, a prompt has arguments, a resource template has a
      // uriTemplate — and picking fields by hand means the next kind of change
      // is the one nobody fingerprinted.
      fingerprints[label] = digest({ label, definition: byLabel.get(label) });
    }
    return { names, fingerprints };
  } finally {
    await client.close();
    await server.close();
  }
}

/**
 * A permission map to start from, priced so it cannot be forgotten.
 *
 * Every capability gets a placeholder no role grants, which `reconcile` reports
 * as unreachable and the boot refuses. The scaffold is deliberately useless
 * until a person has decided what each capability costs — that decision is the
 * whole point of the file, and a default would quietly make it for them.
 *
 * Returned as source rather than written, so the caller chooses where it lands.
 */
export const UNASSIGNED = 'TODO:unassigned';

export function toPermissionsModule(record: CapabilityRecord): string {
  const entries = record.names.map((label) => `  ${quote(label)}: '${UNASSIGNED}',`);
  return [
    '// Generated by recordCapabilities(). Replace every TODO with a real permission.',
    '',
    'export const PERMISSIONS = {',
    ...entries,
    '} as const;',
    '',
    'export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];',
    '',
  ].join('\n');
}

/** Bare where it is a valid identifier, quoted where the label carries a prefix. */
function quote(label: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(label) ? label : `'${label}'`;
}
